### ISSUE TITLE
Possible collisions

### ISSUE THREAD

**Issue by baardkrk** [SAGARobotics/topological_navigation#37]
Without modelling physical barriers cases like this are possible:

![image](https://user-images.githubusercontent.com/6884738/215464261-d3c0955d-51d0-4097-ac71-7d3bc1678f40.png)

The closest node was a the other side of a tunnel wall, but the planner didn't see that as a problem, so it asked the robot to drive straight through. Not sure if this normally is an issue outside of simple simulations?

**Comment by MikHut** [comment]
Closing as this isn't a toponav issue

**Comment by MikHut** [comment]
Closing as this isn't a toponav issue
